/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;


import home.Home;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author djavu
 */
public class Kasir extends javax.swing.JFrame {
    //deklarasi
    
//    static int byr;
//    static int ttl;
    static List <Integer> tHarga = new ArrayList<Integer>();
    DefaultListModel mdlNamaBarang = new DefaultListModel();
    DefaultListModel mdlJumlahHarga = new DefaultListModel();
    JList listBarangHarga = new JList(mdlJumlahHarga);
    int baris =0;
    static Object kolom [] = {"jumlah Item","Total Harga","Tanggal"};
    DefaultTableModel tbl = new DefaultTableModel(kolom, baris);
    List <String> ArrayBarang = new ArrayList<String>();
    ArrayList<Integer> listTable = new ArrayList<>();
    /**
     * Creates new form kasir
     */
    public Kasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tJumlahHarga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tPembelian = new javax.swing.JTable();
        addHargaJumlah = new javax.swing.JButton();
        tSearch = new javax.swing.JTextField();
        btnBayar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tTotalHarga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tBayar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tKembalian = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lNamaBarang = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lHargaJumlah = new javax.swing.JList<>();
        btnClearTable = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnDeleteListBarang = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenu = new javax.swing.JMenu();
        mMenu = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Daftar Nama Barang");

        jLabel2.setText("Barang dan Harga");

        tPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tPembelian);

        addHargaJumlah.setText("Tambah");
        addHargaJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHargaJumlahActionPerformed(evt);
            }
        });

        tSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tSearchKeyReleased(evt);
            }
        });

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        jLabel3.setText("Total harga");

        jLabel4.setText("Bayar");

        tBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tBayarKeyReleased(evt);
            }
        });

        jLabel5.setText("Kembalian");

        lNamaBarang.setBackground(new java.awt.Color(255, 255, 255));
        lNamaBarang.setForeground(new java.awt.Color(0, 0, 0));
        lNamaBarang.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lNamaBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lNamaBarangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lNamaBarang);

        lHargaJumlah.setBackground(new java.awt.Color(255, 255, 255));
        lHargaJumlah.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(lHargaJumlah);

        btnClearTable.setText("clear");
        btnClearTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearTableActionPerformed(evt);
            }
        });

        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnDeleteListBarang.setText("clear");
        btnDeleteListBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteListBarangActionPerformed(evt);
            }
        });

        jmenu.setText("File");

        mMenu.setText("Home");
        mMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mMenuMousePressed(evt);
            }
        });
        jmenu.add(mMenu);

        jMenuBar1.add(jmenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(jLabel1))
                                    .addComponent(addHargaJumlah))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tSearch)
                                    .addComponent(jScrollPane2))
                                .addGap(79, 79, 79)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tJumlahHarga)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnBayar)
                                            .addComponent(tKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tTotalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                            .addComponent(tBayar)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jLabel2))
                            .addComponent(btnDeleteListBarang)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClearTable)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(tJumlahHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(14, 14, 14)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(tBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(tKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBayar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addHargaJumlah)
                    .addComponent(btnDeleteListBarang))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearTable)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
        String[] listBarang = getListBarang();
        for (int i = 0;i<listBarang.length;i++){
            mdlNamaBarang.addElement(listBarang[i]);
            lNamaBarang.setModel(mdlNamaBarang);
        } 
        tTotalHarga.setEditable(false);
        tKembalian.setEditable(false);
        tPembelian.setModel(tbl);
    }//GEN-LAST:event_formComponentShown

    private void lNamaBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lNamaBarangMouseClicked
        // TODO add your handling code here:
        String select = lNamaBarang.getSelectedValue().toString();
        tJumlahHarga.setText(select);
    }//GEN-LAST:event_lNamaBarangMouseClicked

    private void addHargaJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHargaJumlahActionPerformed
        // TODO add your handling code here:
        int index;
        //get list barang
        String[] listBarang = getListBarang();
        
        List <String> ArrayBarang = new ArrayList<String>();
        ArrayBarang = lNamaBarang.getSelectedValuesList();
        String[] ArrBarang = new String [ArrayBarang.size()];
        ArrBarang = ArrayBarang.toArray(ArrBarang);
        String select = lNamaBarang.getSelectedValue();
        
        //call function find index
        index = mencari(listBarang,select);
        Integer[] ArrHarga =getListHarga();
        if (index==-1){
            JOptionPane.showMessageDialog(this, "kesalahan");
        }else{
        for(int i=0; i<ArrayBarang.size(); i++){
            mdlJumlahHarga.addElement(ArrBarang[i]+" @"+ArrHarga[index]);
            lHargaJumlah.setModel(mdlJumlahHarga);
            tHarga.add(ArrHarga[index]);
            
            }
        }
        int hasil = getTotal();
        tTotalHarga.setText(""+hasil);  
    }//GEN-LAST:event_addHargaJumlahActionPerformed

    private void tBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tBayarKeyReleased
        // TODO add your handling code here:
        int kembalian;
        int total_harga = Integer.parseInt(tTotalHarga.getText());
        int bayar = Integer.parseInt(tBayar.getText());
        
        kembalian = getKembalian(bayar, total_harga);
        tKembalian.setText(String.valueOf(kembalian));
    }//GEN-LAST:event_tBayarKeyReleased

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        String total_harga = tTotalHarga.getText().toString();
        Date tgl = new Date();
        int hasil;
        int total_item;
        int row;
        hasil = getTotal();
        total_item = tHarga.size();
        
        if(total_harga.equals("")){
            JOptionPane.showMessageDialog(this, "Data masih kosong");
        }else{
            tbl.addRow(new Object[]{total_item,hasil,tgl});
            tPembelian.setModel(tbl); 
        tTotalHarga.setText("");
        tBayar.setText("");
        tKembalian.setText("");
        clear();
        tHarga.removeAll(tHarga);
        }
        
        
    }//GEN-LAST:event_btnBayarActionPerformed

    private void tSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tSearchKeyReleased

        clearListBarang();
        String[] listBarang = getListBarang();
        String cari = tSearch.getText();
        for (int i =0;i<listBarang.length;i++){
            if (containsIgnoreCase(listBarang[i],cari)){
                mdlNamaBarang.addElement(listBarang[i]);
                lNamaBarang.setModel(mdlNamaBarang);
            }
        }
    }//GEN-LAST:event_tSearchKeyReleased

    private void btnClearTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearTableActionPerformed
        tbl.getDataVector().removeAllElements();
        tbl.fireTableDataChanged();
    }//GEN-LAST:event_btnClearTableActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int  baris = tPembelian.getSelectedRow();
        tbl.removeRow(baris);
        listTable.remove(baris);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnDeleteListBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteListBarangActionPerformed
        // TODO add your handling code here:
        tTotalHarga.setText("");
        tBayar.setText("");
        tKembalian.setText("");
        clear();
        tHarga.removeAll(tHarga);
    }//GEN-LAST:event_btnDeleteListBarangActionPerformed

    private void mMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMenuMousePressed
        // TODO add your handling code here:
        Home home = new Home();
        home.setLocationRelativeTo(this);
        this.setVisible(false);
        home.setVisible(true);
        
    }//GEN-LAST:event_mMenuMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }
    
    //fungsi
    private static int mencari (String[] nilai, String cari){
        for (int i =0;i<nilai.length;i++){
            if (cari.equals(nilai[i])){
                return i;
            }
        }return -1;
    }
    
    static String[] getListBarang(){
        ArrayList<String> listBarang = new ArrayList<>();
        listBarang.add("Mie Sedaap Goreng");
        listBarang.add("Mie Sedaap Kuah");
        listBarang.add("Mie Indomie");
        listBarang.add("Aqua 1500 ml");
        listBarang.add("Aqua 330 ml");
        listBarang.add("Aqua 250 ml");
        listBarang.add("Aqua 600 ml");
        listBarang.add("Le Mineral 330 ml");
        listBarang.add("Le Mineral 600 ml");
        listBarang.add("Le Mineral 1500 ml");
        //convert arraylist to array barang
        String[] ArrBarang = new String [listBarang.size()];
        ArrBarang = listBarang.toArray(ArrBarang);
        return ArrBarang;
    }
    static Integer[] getListHarga(){
        //list harga
        ArrayList<Integer> listHarga = new ArrayList<>();
        listHarga.add(2500);
        listHarga.add(2500);
        listHarga.add(2500);
        listHarga.add(5000);
        listHarga.add(2000);
        listHarga.add(1500);
        listHarga.add(3000);
        listHarga.add(2000);
        listHarga.add(3000);
        listHarga.add(5000);
        //convert arraylist to array harga
        Integer[] ArrHarga = new Integer[listHarga.size()];
        ArrHarga = listHarga.toArray(ArrHarga);
        return ArrHarga;
    }
    
    public static int getKembalian(int byr, int ttl){
        int kembali = byr-ttl;
        return kembali;
    }
   
    public static int getTotal() {
        int hasil = 0;
        for (int harga : tHarga){
                hasil += harga;
            }
        return hasil;
    }

    public void clear(){
         if(mdlJumlahHarga.size() > 0){
         mdlJumlahHarga.removeAllElements();
         mdlJumlahHarga.clear();
         listBarangHarga.removeAll();
         }
        }
    public void clearListBarang(){
         if(mdlNamaBarang.size() > 0){
         mdlNamaBarang.removeAllElements();
         mdlNamaBarang.clear();
         lNamaBarang.removeAll();
         }
        }
    
    public static boolean containsIgnoreCase(String str, String subString) {
        return str.toLowerCase().contains(subString.toLowerCase());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addHargaJumlah;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnClearTable;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteListBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JMenu jmenu;
    private javax.swing.JList<String> lHargaJumlah;
    private javax.swing.JList<String> lNamaBarang;
    private javax.swing.JMenuItem mMenu;
    private javax.swing.JTextField tBayar;
    private javax.swing.JTextField tJumlahHarga;
    private javax.swing.JTextField tKembalian;
    private javax.swing.JTable tPembelian;
    private javax.swing.JTextField tSearch;
    private javax.swing.JTextField tTotalHarga;
    // End of variables declaration//GEN-END:variables
}
